# The URL the site will be built for
base_url = "https://edadaltocg.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feeds = true
generate_sitemap = true
generate_robots_txt = true

ignored_content = ["content/**/{Cargo.lock,target}, *.rs, *.py, *.ipynb"]

title = "Ed's"
description = "Hi there! Welcome to my personal website. I'm an AI researcher with experience in both academia and startups. I co-founded Future Frame in San Francisco and Paris, where we used advanced transformer models to transform data science by removing biases from traditional methods. Our API platform allowed data scientists to easily work with our innovations. I completed my PhD in Machine Learning at CentraleSupélec, focusing on making AI systems more secure and trustworthy, particularly in fields like computer vision and medical imaging. My background includes a research internship in Montreal and degrees from ISAE-SUPAERO and ITA in Brazil. I'm passionate about creating AI that's not only powerful but also truly human-centered and reliable. Thanks for stopping by to learn more about my work!."

feed_filenames = ["atom.xml"]

taxonomies = [
  # You can enable/disable RSS
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# Synthax hightlight
highlight_theme = "css"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

lazy_async_image = true

[search] # Options specific to elasticlunr search.
# index format can be: elasticlunr_json or elasticlunr_javascript or fuse_json
index_format = "elasticlunr_json"
include_title = true              # include title of page/section in index
include_description = true        # include description of page/section in index
include_content = true            # include rendered content of page/section in index
include_path = true
# truncate_content_length = 100 # Truncate at nth character. May be useful if index is getting too large.

[extra]
# Put all your custom variables here
author = "Eduardo Dadalto"
links = [
  { title = "home", href = "/" },
  { title = "publications", href = "/publications" },
  # { title = "bio", href = "/bio" },
  # { title = "blog", href = "/blog" },
  { title = "projects", href = "/projects" },
  { title = "teaching", href = "/teaching" },
  { title = "news", href = "/news" },
  { title = "contact", href = "/contact" },
  { title = "cv", href = "/cv" },
]
footer_menu = [
  # { title = "home", href = "/" },
  { title = "publications", href = "/publications" },
  # { title = "bio", href = "/bio" },
  # { title = "blog", href = "/blog" },
  { title = "projects", href = "/projects" },
  { title = "teaching", href = "/teaching" },
  { title = "news", href = "/news" },
  { title = "contact", href = "/contact" },
  { title = "cv", href = "/cv" },
]
enable_katex = true
logo_home_link = "/"
seo = true # enable or disable seo-related meta tags: opengraph, facebook, twitter
keywords = "eduardo dadalto,research,ai,human-centric ai,trustworthy ai,deep learning,NLP,computer vision" # used for the primary site index
js_prestyle = true
# Socials
github = "edadaltocg"
linkedin = "edadaltocg"
# bluesky = "edadaltocg"
# twitter = "dadalto_eduardo"
docker = "edadaltocg"      #https://hub.docker.com/repositories/edadaltocg"
huggingface = "edadaltocg"
feed = true                # this adds the RSS feed icon in the footer.

# Icons
fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"

favicon_svg = "favicon.ico" # favicon.svg
favicon180 = "apple-touch-icon.png" # apple-touch-icon.png
favicon32 = "favicon-32x32.png" # favicon-32x32.png
favicon16 = "favicon-16x16.png" # favicon-16x16.png
fonts = [
  { url = "https://fonts.googleapis.com/css?family=Roboto:400,700,italic|Roboto+Mono:400,italic" },
]
security_header_referrer = "strict-origin-when-cross-origin"
# security_header_csp = "default-src 'none'; object-src 'none'; base-uri 'self'; manifest-src 'self'; connect-src 'self'; form-action 'self'; script-src 'self'; img-src 'self' data: cdn.cloudflare.com; frame-src 'self' www.youtube-nocookie.com player.vimeo.com; media-src 'self' data: cdn.cloudflare.com www.youtube-nocookie.com player.vimeo.com; font-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.gstatic.com; style-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.googleapis.com;"

# PWA
webmanifest = "manifest.min.json" # Required for PWAs
